'use strict';
/**
 * Artifact 版の全体テスト: node test/artifact-e2e.js
 *  - mock モード: window.claude なし（メモリ上で動く）
 *  - db モード : window.claude.use を疑似ランタイムで注入（db は Node 側に永続、assets/sample/downloads も模擬）
 * 結果を artifact/TEST.md に書き出す。スクリーンショットは test/screens/。
 */
const path = require('path');
const fs = require('fs');
let playwright; try { playwright = require('playwright'); } catch (e) { playwright = require(path.join(require('child_process').execSync('npm root -g').toString().trim(), 'playwright')); }
const FILE = 'file://' + path.join(__dirname, '..', 'artifact', 'index.html');
const OUT = path.join(__dirname, 'screens'); fs.mkdirSync(OUT, { recursive: true });
const T0 = '2026-09-16T06:50:00+08:00';

/* ---------------- 疑似ランタイム（Node 側ストア） ---------------- */
function makeRuntime() {
  const DB = {}, assets = [], downloads = [], sampleCalls = [];
  const rt = { DB, assets, downloads, sampleCalls,
    op(op, a) {
      switch (op) {
        case 'get': return { exists: !!(DB[a.coll] && DB[a.coll][a.id]), data: DB[a.coll] && DB[a.coll][a.id] || null };
        case 'set': (DB[a.coll] = DB[a.coll] || {})[a.id] = JSON.parse(JSON.stringify(a.data)); return null;
        case 'del': if (DB[a.coll]) delete DB[a.coll][a.id]; return null;
        case 'list': return Object.entries(DB[a.coll] || {}).map(([id, data]) => ({ id, data }));
        case 'asset': assets.push(a); return null;
        case 'download': downloads.push(a); return null;
        case 'sample': sampleCalls.push(a); return null;
      }
    } };
  return rt;
}
// ページ側に注入するシム（db/assets/sample/downloads）
const SHIM = `(() => {
  const call = (op, a) => window.__rt(op, a);
  // 自分の書き込みは即スナップショットに反映（実 db の latency compensation を模す）
  const PENDING = {};
  const snap = (id, d) => ({ id, exists: !!d, data: () => d || undefined, metadata: { fromCache: false, hasPendingWrites: false } });
  const merge = (coll, rows) => { const p = PENDING[coll] || {}; const map = {}; rows.forEach(r => { map[r.id] = r.data; }); Object.keys(p).forEach(id => { if (JSON.stringify(map[id] || null) === JSON.stringify(p[id])) delete p[id]; else if (p[id] === null) delete map[id]; else map[id] = p[id]; }); return Object.keys(map).sort().map(id => ({ id, data: map[id] })); };
  const mkColl = (coll) => ({ path: coll,
    doc: (id) => ({ id, path: coll + '/' + id,
      get: async () => { const r = await call('get', { coll, id }); return snap(id, r.exists ? r.data : null); },
      set: async (data) => { (PENDING[coll] = PENDING[coll] || {})[id] = JSON.parse(JSON.stringify(data)); await call('set', { coll, id, data }); },
      update: async (data) => { const r = await call('get', { coll, id }); if (!r.exists) throw { code: 'invalid_argument', message: 'no doc' }; await call('set', { coll, id, data: Object.assign({}, r.data, data) }); },
      delete: async () => { (PENDING[coll] = PENDING[coll] || {})[id] = null; await call('del', { coll, id }); } }),
    onSnapshot: (next, err) => { let last = null, alive = true;
      const tick = async () => { if (!alive) return; const rows = merge(coll, await call('list', { coll })); const j = JSON.stringify(rows); if (j !== last) { last = j; next({ docs: rows.map(r => snap(r.id, r.data)), size: rows.length, empty: !rows.length, docChanges: () => [], metadata: { fromCache: false, hasPendingWrites: false } }); } };
      tick(); const h = setInterval(tick, 150); return () => { alive = false; clearInterval(h); }; } });
  const db = { collection: mkColl, doc: (p) => { const seg = p.split('/'); return mkColl(seg.slice(0, -1).join('/')).doc(seg[seg.length - 1]); } };
  const OPTS = window.__rtOpts || {};
  const assets = { upload: async (blob) => { const id = ('a' + Math.random().toString(36).slice(2)).padEnd(32, '0').slice(0, 32); await call('asset', { id, type: blob.type, size: blob.size }); return { id, url: '/_blob/' + id, sizeBytes: blob.size, contentType: blob.type }; }, list: async () => ({ assets: [], usage: {} }), delete: async () => ({ deleted: true }) };
  const sample = Object.assign(async (input) => ({ text: 'ok', truncated: false, modelTierApplied: 'quick' }), {
    json: async (input, opts) => { opts = opts || {}; const img = opts.images ? (Array.isArray(opts.images) ? opts.images[0] : opts.images) : null; await call('sample', { prompt: String(input).slice(0, 80), hasImage: !!img, imageSize: img ? img.size : 0, imageType: img ? img.type : '', tier: opts.modelTier || '' });
      if (img) { if (/BAD/.test(input)) return { oops: 'not the shape' }; return { items: [{ name_ja: '白ご飯', name_en: 'White rice', grams: 200, kcal: 312, p: 5, f: 1, c: 69 }, { name_ja: '鶏の唐揚げ', name_en: 'Fried chicken', grams: 120, kcal: 340, p: 20, f: 22, c: 12 }], total: { kcal: 652, p: 25, f: 23, c: 81 }, confidence: 'medium', note: '皿の大きさから推定' }; }
      if (/meal note/.test(input)) return [{ foodId: 'salmon', nameJa: 'サーモン', nameEn: 'Salmon', amount: 150, kcal: 0, p: 0, f: 0, c: 0, note: '' }, { foodId: null, nameJa: '納豆', nameEn: 'Natto', amount: 45, kcal: 190, p: 16.5, f: 10, c: 12.1, note: '1 pack' }];
      return { nameJa: '納豆', nameEn: 'Natto', kcal: 190, p: 16.5, f: 10, c: 12.1, note: '1 pack' }; },
    limits: async () => (OPTS.noImages ? { maxPromptBytes: 65536 } : { maxPromptBytes: 65536, images: { maxCount: 1, maxInputBytes: 20000000, mediaTypes: ['image/jpeg', 'image/png', 'image/webp'] } }) });
  const downloads = { save: async (req) => { await call('download', { filename: req.filename, size: String(req.data).length, head: String(req.data).slice(0, 200) }); return { status: 'saved' }; } };
  window.claude = { use: async (name) => ({ db, assets: OPTS.noAssets ? null : assets, sample, downloads })[name] || null };
})();`;

/* ---------------- テスト実行 ---------------- */
const results = []; // {group, name, mock, db, note}
function rec(group, name, mode, ok, note) { let r = results.find(x => x.group === group && x.name === name); if (!r) { r = { group, name, mock: '—', db: '—', note: '' }; results.push(r); } r[mode] = ok ? '✓' : '✗'; if (note) r.note = (r.note ? r.note + ' / ' : '') + note; }
async function run(mode) {
  const rt = makeRuntime();
  const browser = await playwright.chromium.launch({ executablePath: process.env.PW_CHROMIUM || undefined });
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, timezoneId: 'Asia/Manila' });
  const errors = [];
  const newPage = async (opts) => {
    const page = await ctx.newPage();
    if (opts) await page.addInitScript('window.__rtOpts = ' + JSON.stringify(opts) + ';');
    page.setDefaultTimeout(8000);
    await page.clock.setFixedTime(new Date(T0));
    page.on('pageerror', e => errors.push('pageerror: ' + e.message));
    page.on('console', m => { if (m.type() === 'error' && !/fonts.googleapis|ERR_/.test(m.text())) errors.push('console: ' + m.text()); });
    page.on('dialog', d => d.accept(d.type() === 'prompt' ? (d.message().includes('代替') ? 'フロアプレス' : d.message().includes('理由') ? '時間がない' : '25') : undefined));
    await page.route('https://fonts.googleapis.com/**', r => r.fulfill({ status: 200, contentType: 'text/css', body: '' }));
    if (mode === 'db') { await page.exposeFunction('__rt', (op, a) => rt.op(op, a)); await page.addInitScript(SHIM); }
    await page.goto(FILE);
    await page.waitForFunction(() => !document.querySelector('#view .loading'), null, { timeout: 15000 });
    return page;
  };
  // 前回値（9/9 = Day1）を db に仕込む: インクライン トップ 22×8（上限到達）, サイドレイズ メイン 10×12（上限到達）
  if (mode === 'db') rt.op('set', { coll: 'log_workout', id: '2026-09-09', data: { date: '2026-09-09', sets: { '2_2': { exerciseId: 2, setNo: 2, setType: 'TOP', weightKg: 22, reps: 8 }, '5_1': { exerciseId: 5, setNo: 1, setType: 'MAIN', weightKg: 10, reps: 12 }, '1_1': { exerciseId: 1, setNo: 1, setType: 'MAIN', weightKg: 8, reps: 12 } }, meta: {}, warmup: { done: '08:40' } } });
  let page = await newPage();
  const text = async (sel) => (await page.locator(sel).first().textContent()).trim();
  const has = async (sel) => !!(await page.$(sel));
  const shot = async (n) => { await page.waitForTimeout(150); await page.screenshot({ path: path.join(OUT, 'art-' + mode + '-' + n + '.png'), fullPage: true }); };
  const cleanup = async () => { try { if (await has('#dlg:not([hidden])')) { await page.click('#dlg', { position: { x: 5, y: 5 } }); await page.waitForTimeout(80); } if (await has('#sheet:not([hidden])')) { await page.click('#sheet', { position: { x: 5, y: 5 } }); await page.waitForSelector('#sheet', { state: 'hidden' }); } if (await has('#rest:not([hidden])')) { await page.click('#skipRest'); } await page.waitForTimeout(100); } catch (e) { /* ignore */ } };
  const T = async (group, name, fn) => { try { const note = await fn(); rec(group, name, mode, true, typeof note === 'string' ? note : ''); console.log('ok   [' + mode + '] ' + name); } catch (e) { rec(group, name, mode, false, e.message); console.error('FAIL [' + mode + '] ' + name + ': ' + e.message); } await cleanup(); };
  const assert = (c, m) => { if (!c) throw new Error(m || 'assert'); };
  const setTime = async (iso) => { await page.clock.setFixedTime(new Date(iso)); };
  const goTab = async (tab) => { await page.click('.tabs [data-tab="' + tab + '"]'); await page.waitForTimeout(120); };
  const closeSheet = async () => { if (await has('#sheet:not([hidden])')) { await page.click('#sheet', { position: { x: 5, y: 5 } }); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(150); } };
  const gotoEx = async (i) => { for (let g = 0; g < 12; g++) { if (await has('#rest:not([hidden])')) { await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])'); } const m = /種目 (\d+)\//.exec(await text('.ex-head .p')); const cur = Number(m[1]) - 1; if (cur === i) return; await page.click('[data-ex="' + (cur < i ? 1 : -1) + '"]'); await page.waitForTimeout(60); } throw new Error('gotoEx ' + i); };
  const dlgOk = async (fillText) => { await page.waitForSelector('#dlg:not([hidden])'); if (fillText != null) { await page.fill('#dlgIn', fillText); } await page.click('#dlgOk'); await page.waitForSelector('#dlg', { state: 'hidden' }); await page.waitForTimeout(120); };
  const mark = async (id) => page.$eval('[data-step="' + id + '"]', e => e.dataset.mark + '|' + e.querySelector('.chk').className + '|' + e.querySelector('.chk').textContent);
  const pickReason = async (label) => { await page.waitForSelector('[data-reason]'); await page.click('[data-reason="' + label + '"]'); await page.waitForFunction(() => document.querySelector('#dlg').hidden || !document.querySelector('[data-reason]')); await page.waitForTimeout(80); };
  const G = { today: '今日画面', missed: '欠測・できなかった', workout: '筋トレ画面', meal: '食事シート', week: '週画面', common: '共通' };

  // ============ 共通（先に） ============
  await T(G.common, 'db が null でもモックモードで動き「保存されていません」の帯が出る', async () => { if (mode === 'mock') assert((await text('.mode')).includes('保存されていません'), 'banner'); else assert(!(await has('.mode')), 'no banner in db'); });
  await T(G.common, 'タブは 今日・筋トレ・水・週 の 4 つ', async () => { const tabs = await page.$$eval('.tabs button', els => els.map(e => e.dataset.tab)); assert(JSON.stringify(tabs) === '["today","workout","water","summary"]', tabs.join()); const labels = await page.$$eval('.tabs button .ic', els => els.map(e => e.textContent)); assert(labels.join(',') === '今日,筋トレ,水,週', labels.join(',')); });
  await T(G.common, '375〜430px で横スクロールなし・下タブが safe-area にかぶらない', async () => { for (const w of [375, 390, 430]) { await page.setViewportSize({ width: w, height: 844 }); await page.waitForTimeout(60); const sw = await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1); assert(sw, 'hscroll at ' + w); } await page.setViewportSize({ width: 390, height: 844 }); const pb = await page.$eval('.tabs', e => getComputedStyle(e).paddingBottom); return 'tabs padding-bottom=' + pb + '（env(safe-area-inset-bottom) 加算）'; });

  // ============ 今日画面 ============
  await T(G.today, '日付 ‹ › で前日・翌日へ移動し、今日に戻れる', async () => { await page.click('[data-shift="1"]'); assert((await text('.date')).includes('9/17'), 'next'); await page.click('[data-shift="-1"]'); await page.click('[data-shift="-1"]'); assert((await text('.date')).includes('9/15'), 'prev'); await page.click('[data-shift="1"]'); assert((await text('.date')).includes('9/16') && !(await text('.date')).includes('過去'), 'back to today'); });
  await T(G.today, 'Day 判定: 9/16=Day1 … 9/22=Day7 → 9/23=Day1', async () => { const want = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7', 'Day 1']; for (let i = 0; i < 8; i++) { assert((await text('h1')).startsWith(want[i]), '9/' + (16 + i) + ' → ' + (await text('h1'))); if (i < 7) await page.click('[data-shift="1"]'); } for (let i = 0; i < 7; i++) await page.click('[data-shift="-1"]'); assert((await text('h1')).startsWith('Day 1'), 'back'); });
  await T(G.today, '全行で「…」省略なし。サプリ名・食材が全部表示', async () => { const rows = await page.$$eval('.step', els => els.map(e => e.textContent)); assert(!rows.some(r => r.includes('…')), 'ellipsis'); assert(rows.some(r => r.includes('B12＋D3') && r.includes('ベルベリン') && r.includes('フィッシュオイル') && r.includes('クレアチン')), 'supp names (after meal)'); assert(rows.some(r => r.includes('マグネシウム グリシネート 400mg 就寝前') && r.includes('アシュワガンダ 300mg 就寝前')), 'night supps with dose'); assert(rows.some(r => r.includes('腹筋 ・ カーフ') && r.includes('コーチ確認待ち')), 'abs/calves row'); assert(rows.some(r => r.includes('全卵4個・卵白150g・塩1g')), 'meal1 items'); assert(rows.some(r => r.includes('ケーブルフライ または ペックデッキ（事前疲労）・インクラインダンベルプレス') && r.includes('スーパーセット') && r.includes('アンダーハンド')), 'exercises'); });
  await T(G.today, '体重 kg⇄lb 切替で換算が正しく、保存は kg', async () => { await goTab('summary'); await page.click('#unitBtn'); await page.waitForTimeout(100); await goTab('today'); assert((await text('#now .w-in .u')) === 'lb', 'unit lb'); await page.fill('#nowW', '160'); await page.click('#nowBtn'); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').className.includes('done')); const row = await text('[data-step="weight"]'); assert(row.includes('160.1lb') || row.includes('160lb'), 'lb display: ' + row); if (mode === 'db') { await page.waitForTimeout(200); assert(rt.DB.log_weight['2026-09-16'].weightKg === 72.6, 'stored kg=' + rt.DB.log_weight['2026-09-16'].weightKg); } await goTab('summary'); await page.click('#unitBtn'); await page.waitForTimeout(100); await goTab('today'); assert((await text('[data-step="weight"]')).includes('72.6kg'), 'kg display'); return '160lb → 72.6kg 保存'; });
  await T(G.today, 'リンゴ酢✓ → 15分タイマー → 「いま」が1食目に変わる', async () => { await page.click('[data-chk="routine:1"]'); await page.waitForSelector('#nowTimer'); assert((await text('#now .t')) === '1食目まで', 'timer title'); assert((await text('#nowTimer')) === '15:00', 'timer 15:00'); assert((await text('[data-step="meal:1"] .tm')).includes('07:05') && (await text('[data-step="meal:1"] .tm')).includes('タイマー'), 'row shows timer end 07:05');
    if (mode === 'db') { await page.waitForTimeout(250); await setTime('2026-09-16T06:55:30+08:00'); await page.reload(); await page.waitForFunction(() => !document.querySelector('#view .loading')); await goTab('today'); await page.waitForSelector('#nowTimer'); const left = await text('#nowTimer'); assert(/^9:(2|3)\d$/.test(left), 'after reload remaining ~9:30: ' + left); } await setTime('2026-09-16T07:06:00+08:00'); await goTab('workout'); await goTab('today'); assert((await text('#now .t')) === '1食目を食べる', 'after 15min: ' + (await text('#now .t'))); });
  await T(G.today, '✓の付け外しが即反映、再読み込み後も残る（db）', async () => { await page.click('[data-chk="meal:1"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:1"]').className.includes('done')); await page.click('[data-chk="routine:1"]'); await page.waitForFunction(() => !document.querySelector('[data-step="routine:1"]').className.includes('done')); await page.click('[data-chk="routine:1"]'); await page.waitForFunction(() => document.querySelector('[data-step="routine:1"]').className.includes('done'));
    if (mode === 'db') { await page.waitForTimeout(300); await page.reload(); await page.waitForFunction(() => !document.querySelector('#view .loading')); await goTab('today'); assert((await page.$eval('[data-step="meal:1"]', e => e.className)).includes('done'), 'meal1 after reload'); assert((await page.$eval('[data-step="weight"]', e => e.className)).includes('done'), 'weight after reload'); return '再読み込み後も維持'; } return 'モックは再読み込み対象外'; });
  await T(G.today, 'サプリ✓ → 15分後にサイリウムが「いま」になる', async () => { await setTime('2026-09-16T07:20:00+08:00'); await goTab('workout'); await goTab('today'); await page.click('[data-chk="supp:after_meal"]'); await page.waitForFunction(() => document.querySelector('[data-step="supp:after_meal"]').className.includes('done')); assert((await text('#now .t')) === 'サイリウムまで', 'timer to psyllium: ' + (await text('#now .t'))); await setTime('2026-09-16T07:36:00+08:00'); await goTab('workout'); await goTab('today'); assert((await text('#now .t')) === 'サイリウム', 'now psyllium: ' + (await text('#now .t'))); await page.click('#nowBtn'); await page.waitForFunction(() => document.querySelector('[data-step="routine:2"]').className.includes('done')); });
  await T(G.today, '水タブ: 目標 5.0L・大数字・+500/+350/−500・達成で緑「5L 達成！」・log_daily.waterMl に保存', async () => { await page.click('[data-open="water"]'); await page.waitForSelector('#waterBig'); assert((await page.$eval('.tabs .on', e => e.dataset.tab)) === 'water', 'row tap opens water tab'); assert((await text('.card .ttl')).includes('目標 5.0 L'), 'goal'); await page.click('[data-w="500"]'); await page.click('[data-w="350"]'); await page.waitForFunction(() => document.querySelector('#waterBig').textContent.startsWith('0.85')); assert((await text('#waterStat')).includes('あと 4.15 L'), 'left'); await page.click('[data-w="-500"]'); await page.waitForFunction(() => document.querySelector('#waterBig').textContent.startsWith('0.35')); for (let i = 0; i < 10; i++) await page.click('[data-w="500"]'); await page.waitForFunction(() => document.querySelector('#waterBig').textContent.startsWith('5.35')); assert((await text('#waterStat')) === '5L 達成！' && (await page.$eval('#waterStat', e => getComputedStyle(e).color)) === (await page.$eval('#waterBig', e => getComputedStyle(e).color)), 'achieved in green'); assert(/^5\.[34] L$/.test(await text('#tabWater')), 'tab sub: ' + (await text('#tabWater'))); if (mode === 'db') { await page.waitForTimeout(200); assert(rt.DB.log_daily['2026-09-16'].waterMl === 5350, 'log_daily.waterMl: ' + JSON.stringify(rt.DB.log_daily['2026-09-16'])); } await goTab('today'); const row = await text('[data-step="water"]'); assert(row.includes('達成'), 'water row: ' + row); assert((await page.$eval('[data-step="water"]', e => e.className)).includes('done'), 'done'); });
  await T(G.today, '1日合計 kcal/PFC が記録と一致（1食目を手計算で検算）', async () => { const t = await text('.card .ttl'); assert(t.includes('1日合計'), 'block'); const body = await page.$eval('.card', e => e.textContent); // 1食目: 全卵200g=286kcal P25.2 F19 C1.4 + 卵白150g=78 P16.35 F0.3 C1.05 + 塩0 → 364 / P41.6 F19.3 C2.45
    assert(body.includes('カロリー 364'), 'kcal 364: ' + body.slice(0, 120)); assert(body.includes('タンパク質 42'), 'P 42'); assert(body.includes('脂質 19'), 'F 19'); assert(body.includes('炭水化物 2 '), 'C 2'); return '1食目 = 364kcal / P41.6 F19.3 C2.45 と一致'; });
  await shot('01-home');

  // ============ 食事シート ============
  await T(G.meal, '「プラン通り食べた」で今日の✓が付き合計に反映', async () => { await page.click('[data-open="meal:2"]'); await page.waitForSelector('#mPlan'); await page.click('#mPlan'); await page.waitForSelector('#sheet', { state: 'hidden' }); assert((await page.$eval('[data-step="meal:2"]', e => e.className)).includes('done'), 'done'); const body = await page.$eval('.card', e => e.textContent); assert(body.includes('カロリー 968'), 'total 364+604=968: ' + body.slice(0, 80)); });
  await T(G.meal, 'ソフト削除・↩戻す・元に戻すトースト・1つ戻す・プランに戻す', async () => {
    await page.click('[data-open="meal:2"]'); await page.waitForSelector('#mChange'); await page.click('#mChange'); await page.click('[data-q="0"]'); await page.waitForSelector('#pendOk');
    assert((await text('.pending')).includes('サーモン150g を追加'), 'pending add'); await page.click('#pendOk'); await page.waitForSelector('.toast.act'); assert((await text('#toast')).includes('サーモン150g を追加しました'), 'toast'); await page.waitForSelector('[data-del]');
    await page.click('[data-del]'); await page.waitForSelector('[data-undel]'); assert(await has('.list .it.del'), 'soft deleted (strike)'); assert((await text('#toast')).includes('削除しました'), 'del toast');
    await page.click('[data-undel]'); await page.waitForSelector('[data-del]'); assert(!(await has('.list .it.del')), 'restored');
    await page.click('[data-del]'); await page.waitForSelector('[data-undel]'); await page.click('#toast button'); await page.waitForSelector('[data-del]'); assert(!(await has('.list .it.del')), 'toast undo restored');
    await page.click('#mUndo'); await page.waitForTimeout(150); assert(!(await has('[data-del]')), '1つ戻す → 追加前'); 
    await page.click('[data-eat="0"]'); await page.waitForFunction(() => !document.querySelector('[data-eat="0"]').classList.contains('on')); assert((await text('.sheet-body .badge')).includes('変更して記録済み'), 'uncheck → sub');
    await page.click('#mReset'); await dlgOk(); assert((await text('.sheet-body .badge')).includes('プラン通り 記録済み'), 'プランの内容に戻す → プラン通り: ' + (await text('.sheet-body .badge'))); await closeSheet(); });
  await T(G.meal, '差替えチップの置き換え/追加が意図通り。サーモンがプラン本体に混入しない', async () => { await page.click('[data-open="meal:3"]'); await page.waitForSelector('#mPlan'); const plan = await text('.sheet-body .items'); assert(!plan.includes('サーモン'), 'salmon not in plan'); await page.click('#mChange'); const chips = await page.$$eval('[data-q]', els => els.map(e => e.textContent)); assert(chips.some(c => c.includes('サーモン 150g')), 'salmon chip'); await page.click('[data-half]'); await page.waitForSelector('#pendOk'); assert((await text('.pending')).includes('半分の量に置き換え'), 'half pending'); await page.click('#pendOk'); await page.waitForTimeout(200); assert((await text('.sheet-body .list')).includes('（プラン 150）'), 'grams replaced with plan note'); assert((await text('.sheet-body .badge')).includes('変更して記録済み'), 'sub'); await closeSheet(); });
  await T(G.meal, '自由入力→AI計算→foods に source:"ai" 追加→再利用。sample が null なら手入力に切替', async () => { await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mChange'); await page.click('#mChange');
    if (mode === 'mock') { assert((await text('#freeBtn')) === '記録', 'no AI → 記録'); assert(await has('#manualBtn'), 'manual link'); await page.fill('#freeTxt', 'サーモン150 米150'); await page.click('#freeBtn'); await page.waitForSelector('.toast.act'); assert((await text('#toast')).includes('サーモン150g を追加、白米150g（炊飯後基準） を追加'), 'local match: ' + (await text('#toast'))); await closeSheet(); return 'sample null → 手入力／ローカル一致のみ'; }
    assert((await text('#freeBtn')) === 'AI 計算', 'AI button'); await page.fill('#freeTxt', 'サーモン150 納豆45'); await page.click('#freeBtn'); await page.waitForSelector('.toast.act'); assert((await text('#toast')).includes('納豆45g を追加'), 'ai added: ' + (await text('#toast'))); await page.waitForTimeout(200); assert(rt.DB.foods.natto && rt.DB.foods.natto.source === 'ai', 'foods natto source=ai'); const n1 = rt.sampleCalls.length;
    await page.fill('#freeTxt', '納豆45'); await page.click('#freeBtn'); await page.waitForSelector('.toast.act'); await page.waitForTimeout(200); assert(rt.sampleCalls.length === n1, 'reuse without AI call'); await closeSheet(); return 'AI 呼び出し ' + rt.sampleCalls.length + ' 回（2 回目はローカル一致で 0 回）'; });
  await T(G.meal, '4食目の代替案（白米150・鶏100・全卵1）を選べる', async () => { await page.click('[data-open="meal:4"]'); await page.waitForSelector('#mAlt'); assert((await text('#mAlt')).includes('白米150g・鶏胸肉100g・全卵1個'), 'alt label'); await page.click('#mAlt'); await page.waitForSelector('#sheet', { state: 'hidden' }); assert((await text('[data-step="meal:4"]')).includes('代替案で記録'), 'alt logged'); });
  await T(G.meal, '米の基準（生/炊飯後）表示が settings に連動', async () => { assert((await text('[data-step="meal:3"]')).includes('炊飯後基準'), 'cooked default'); await goTab('summary'); await page.click('#riceBtn'); await page.waitForTimeout(150); await goTab('today'); assert((await text('[data-step="meal:2"]')).includes('生米基準'), 'raw after toggle'); assert((await text('.card .ttl')).includes('生米基準'), 'totals note'); await goTab('summary'); await page.click('#riceBtn'); await page.waitForTimeout(150); await goTab('today'); });
  await T(G.meal, '状態4種の表示: 未記録○ / プラン通り緑✓ / 変更あり黄✓ / スキップ赤−', async () => { await page.click('[data-open="meal:3"]'); await page.waitForSelector('#mChange'); await page.click('#mChange'); await page.click('[data-skip]'); await pickReason('外食'); await page.waitForSelector('#pendOk'); assert((await text('.pending')).includes('外食'), 'pending shows reason'); await page.click('#pendOk'); await page.waitForTimeout(150); await closeSheet();
    let m = await mark('meal:3'); assert((await text('[data-step="meal:3"]')).includes('スキップ（外食）'), 'row shows skip reason'); assert(m.startsWith('skip|chk skip|−'), 'skip mark: ' + m); assert((await text('[data-step="meal:3"] .lbl-sub')) === 'スキップ', 'skip label'); assert(!(await page.$('[data-step="meal:3"] .chk.on')), 'no green check on skip');
    await page.click('[data-open="meal:2"]'); await page.waitForSelector('#mChange'); m = await mark('meal:2'); await closeSheet(); assert(m.startsWith('ok|chk on|✓'), 'plan mark: ' + m);
    await page.click('[data-open="meal:4"]'); await page.waitForSelector('#mChange'); await page.click('#mChange'); await page.click('[data-q="0"]'); await page.waitForSelector('#pendOk'); await page.click('#pendOk'); await page.waitForTimeout(150); await closeSheet(); m = await mark('meal:4'); assert(m.startsWith('sub|chk sub|✓'), 'sub mark: ' + m); assert((await text('[data-step="meal:4"] .lbl-sub')) === '変更あり', 'sub label');
    // 5食目は前のテストで変更ありになっているので、✓再タップで取り消して未記録○を確認
    await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === ''); m = await mark('meal:5'); assert(m.startsWith('|chk|'), 'unlogged mark: ' + m); });
  await T(G.meal, 'スキップ→取り消し→プラン通り→取り消し→変更→取り消し: 毎回 未記録に戻り合計が0', async () => {
    // 5食目で往復。合計は 5食目分だけ見る（他の食事は記録済みなので差分で確認）
    const total = async () => Number((await page.$eval('.card', e => e.textContent)).match(/カロリー ([\d,]+)/)[1].replace(/,/g, ''));
    const base = await total();
    const cancelViaSheet = async () => { await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mCancel'); await page.click('#mCancel'); await dlgOk(); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(150); assert((await mark('meal:5')).startsWith('|chk|'), 'back to unlogged'); assert((await total()) === base, 'total back to base ' + base + ': ' + (await total())); if (mode === 'db') assert(!(rt.DB.log_meals['2026-09-16'].meals || {})[5], 'db doc removed'); };
    await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mChange'); await page.click('#mChange'); await page.click('[data-skip]'); await pickReason('時間なし'); await page.waitForSelector('#pendOk'); await page.click('#pendOk'); await page.waitForTimeout(150); await closeSheet(); assert((await mark('meal:5')).startsWith('skip|'), 'skip'); await cancelViaSheet();
    await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === 'ok'); assert((await total()) > base, 'plan adds kcal'); await cancelViaSheet();
    await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mChange'); await page.click('#mChange'); await page.click('[data-half]'); await page.waitForSelector('#pendOk'); await page.click('#pendOk'); await page.waitForTimeout(150); await closeSheet(); assert((await mark('meal:5')).startsWith('sub|'), 'sub'); 
    // 今日画面の✓再タップでも取り消し（トースト＋元に戻す）
    await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === ''); assert((await text('#toast')).includes('5食目の記録を取り消しました'), 'toast'); assert((await total()) === base, 'total base after chk cancel'); await page.click('#toast button'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === 'sub'); assert((await total()) > base, 'undo restored'); await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === ''); return 'base=' + base + ' kcal に毎回戻る'; });
  await T(G.today, '実績時刻: 記録済みは太字＋「予定」、未記録は「予定」薄字、60分以上ズレは黄色', async () => { const w = await page.$eval('[data-step="weight"] .tm', e => ({ b: e.querySelector('b') && e.querySelector('b').textContent, s: e.querySelector('small') && e.querySelector('small').textContent, late: !!e.querySelector('b.late') })); assert(w.b === '06:50' && w.s === '予定 06:40' && !w.late, 'weight tm ' + JSON.stringify(w));
    const m2 = await page.$eval('[data-step="meal:2"] .tm', e => ({ b: e.querySelector('b') && e.querySelector('b').textContent, late: !!e.querySelector('b.late') })); assert(m2.b === '07:36' && m2.late, 'meal2 logged 07:36 vs plan 10:30 → late: ' + JSON.stringify(m2));
    const un = await text('[data-step="meal:5"] .tm'); assert(un.includes('19:30') && un.includes('予定') && !(await page.$('[data-step="meal:5"] .tm b')), 'unlogged shows planned: ' + un); });
  await T(G.today, '記録済み時刻をタップして手修正できる（時刻ピッカー）', async () => { await page.click('[data-time="meal:2"]'); await page.waitForSelector('#dlgTime'); await page.fill('#dlgTime', '10:40'); await page.click('#dlgOk'); await page.waitForSelector('#dlg', { state: 'hidden' }); await page.waitForTimeout(150); const m2 = await page.$eval('[data-step="meal:2"] .tm', e => ({ b: e.querySelector('b').textContent, late: !!e.querySelector('b.late') })); assert(m2.b === '10:40' && !m2.late, 'edited: ' + JSON.stringify(m2)); if (mode === 'db') { await page.waitForTimeout(200); assert(/T10:40/.test(rt.DB.log_meals['2026-09-16'].meals[2].loggedAt), 'loggedAt saved ' + rt.DB.log_meals['2026-09-16'].meals[2].loggedAt); } await page.click('[data-open="meal:2"]'); await page.waitForSelector('#mTime'); assert((await text('.sheet-body h3')).includes('予定 10:30') && (await text('.sheet-body h3')).includes('記録 10:40'), 'sheet header: ' + (await text('.sheet-body h3'))); await closeSheet(); });
  await T(G.today, '「いま」カード右上は現在時刻（1分ごと更新）、予定時刻は別表示', async () => { assert((await text('#nowClock')) === '07:36', 'clock ' + (await text('#nowClock'))); await setTime('2026-09-16T07:41:00+08:00'); await page.waitForFunction(() => document.querySelector('#nowClock').textContent === '07:41', null, { timeout: 70000 }); assert((await text('#now .k')).includes('予定'), 'planned shown separately'); });
  await shot('02-meal');

  // ============ 筋トレ ============
  await T(G.workout, '必ずウォームアップから始まり、6種が完了扱いになるまで「筋トレを始める」が押せない', async () => { await goTab('workout'); await page.waitForSelector('#wuStart'); assert((await text('.cur-set .n')).includes('ウォームアップ 6種'), 'warmup first'); assert((await text('#wuProg')).includes('6種中 0種 完了'), 'progress'); await page.click('#wuStart'); await page.waitForTimeout(100); assert(await has('#wuStart'), 'still warmup'); assert((await text('#toast')).includes('ウォームアップがまだです'), 'blocked toast'); });
  await T(G.workout, 'アニメーション・3ステップ・動画リンク・セットカウンターが6種すべてで動く', async () => { const n = await page.$$eval('.wu', els => els.length); assert(n === 6, '6 cards'); const anims = await page.$$eval('.wu svg.anim', els => els.map(e => e.className.baseVal)); assert(anims.length === 6 && new Set(anims).size === 6, 'six distinct animations: ' + anims.join(',')); const running = await page.$$eval('.wu svg .armL, .wu svg .pelvis, .wu svg .upper', els => els.map(e => getComputedStyle(e).animationName).filter(a => a && a !== 'none').length); assert(running >= 6, 'css animations running: ' + running); const steps = await page.$$eval('.wu ol', els => els.map(e => e.querySelectorAll('li').length)); assert(steps.every(x => x === 3), '3 steps each'); const links = await page.$$eval('.wu .vid a', els => els.map(e => e.href)); assert(links.length === 6 && links.every(l => l.includes('youtube.com/results') && l.includes('warm')), 'video links');
    for (let id = 1; id <= 6; id++) { await page.click('[data-wuset="' + id + '"]'); await page.waitForFunction(i => document.querySelector('#wu' + i + ' .sc').textContent.includes('1/3'), id); await page.click('[data-wuset="' + id + '"]'); await page.waitForFunction(i => document.querySelector('#wu' + i + ' .sc').textContent.includes('2/3'), id); }
    assert((await text('#wuProg')).includes('6種中 6種 完了'), '2/3 counts as done'); await page.click('[data-wuset="1"]'); await page.waitForFunction(() => document.querySelector('#wu1 .sc').classList.contains('ok')); assert(await page.$eval('[data-wuset="1"]', e => e.disabled), '3/3 disables'); await page.click('[data-wuundo="1"]'); await page.waitForFunction(() => document.querySelector('#wu1 .sc').textContent.includes('2/3')); await shot('03-warmup'); await page.click('#wuStart'); await page.waitForSelector('#acNext'); if (mode === 'db') { await page.waitForTimeout(200); const w = rt.DB.log_workout['2026-09-16'].warmup; assert(w.done && w.minutes >= 1, 'warmup minutes saved: ' + JSON.stringify(w)); return 'minutes=' + w.minutes; } });
  await T(G.workout, 'ウォームアップ直後に 腹筋・カーフ 画面（内容はコーチ確認待ち）→「次へ」で種目1へ。休みの日は出ない', async () => { const body = await text('#view'); assert(body.includes('腹筋') && body.includes('カーフ: スミス カーフレイズ') && body.includes('コーチ確認待ち'), 'abs/calves screen'); assert(!(await has('#setDone')), 'exercise not yet'); await page.click('[data-ac="calves"]'); await page.waitForSelector('[data-ac="calves"].on'); await page.click('#acNext'); await page.waitForSelector('#setDone'); assert((await text('.ex-head .p')).includes('種目 1/8'), 'now exercise 1'); await goTab('today'); const row = await text('[data-step="abscalves"]'); assert(row.includes('カーフ ✓') && row.includes('腹筋（内容はコーチ確認待ち）'), 'today row: ' + row); assert((await mark('abscalves')).startsWith('ok|'), 'row done after 次へ'); if (mode === 'db') { await page.waitForTimeout(200); const ac = rt.DB.log_workout['2026-09-16'].absCalves; assert(ac.doneAt && ac.calves.done && !(ac.abs || {}).done, 'absCalves ' + JSON.stringify(ac)); } await goTab('workout'); await page.waitForSelector('#setDone'); });
  await T(G.workout, 'セット一覧（完了=実績値、現在=黄、未=薄）、タップで前セットに戻れる', async () => { assert((await text('.setrows .sr.cur')).includes('← いまここ'), 'cur'); assert((await text('.ghost')).includes(mode === 'db' ? '前回' : '初回なので目安なし'), 'ghost'); if (mode === 'mock') await page.click('[data-qk="10"]'); await page.click('#setDone'); await page.waitForSelector('#rest:not([hidden])'); { const rw = await text('#rn'); assert(rw === '2:30' || rw === '2:29', 'pre-exhaust main rest 150s: ' + rw); } await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])'); const done = await text('.setrows .sr.done .rv'); assert(/kg×1\d/.test(done), 'done row actual: ' + done); assert((await text('.setrows .sr.cur .nm')).includes('セット2'), 'moved to set2'); await page.click('[data-set="0"]'); await page.waitForTimeout(100); assert((await text('.setrows .sr.cur .nm')).includes('セット1'), 'back to set1'); assert((await text('.ghost')).includes('記録済み'), 'shows recorded'); await page.click('[data-set="1"]'); });
  await T(G.workout, '前回値なし→クイック重量ボタン。前回値あり→提案（トップ 上限到達で+kg、バックオフ トップ×0.85、ドロップ 直前×0.7）', async () => { await gotoEx(1); assert((await text('.ex-name')).includes('インクライン'), 'ex2');
    if (mode === 'mock') { assert(await has('[data-qk]'), 'quick buttons'); return '前回値なし → クイック重量'; }
    await page.click('[data-set="1"]'); await page.waitForTimeout(80); const g = await text('.ghost'); assert(g.includes('前回 09-09 22kg×8') && g.includes('23kg') && g.includes('上限到達'), 'TOP suggest: ' + g); assert((await text('#wv')) === '23', 'wv 23');
    await page.click('[data-set="2"]'); await page.waitForTimeout(80); assert((await text('.cur-set .n')).includes('バックオフ'), 'back-off set'); assert((await text('#wv')) === '20', 'BO 23×0.85=20: ' + (await text('#wv'))); assert((await text('.cur-set .p')).includes('15% ほど軽く') && (await text('.cur-set .p')).includes('目安 20kg'), 'BO purpose: ' + (await text('.cur-set .p')));
    await gotoEx(5); assert((await text('.ex-name')).includes('サイドレイズ'), 'ex5'); await page.click('[data-set="0"]'); await page.waitForTimeout(80); assert((await text('#wv')) === '11', 'MAIN 10×12(上限)→11: ' + (await text('#wv'))); await page.click('[data-set="3"]'); await page.waitForTimeout(80); assert((await text('.cur-set .n')).includes('ドロップセット'), 'drop set'); assert((await text('#wv')) === '8', 'DROP 直前 11×0.7=8: ' + (await text('#wv'))); assert((await text('.cur-set .p')).includes('直後') && (await text('.cur-set .p')).includes('−30%') && (await text('.cur-set .p')).includes('目安 8kg'), 'DROP purpose: ' + (await text('.cur-set .p'))); await gotoEx(0); return 'トップ 22×8(上限)→23kg / バックオフ 23×0.85=20kg / メイン 10×12(上限)→11kg / ドロップ 11×0.7=8kg'; });
  await T(G.workout, 'Day1 確定版: 8種目、スーパーセットは 1-1→1-2 を休憩なし、プログレッシブ説明、ドロップは休憩なしで即開始', async () => { assert((await text('.ex-head .p')).includes('/8'), '8 exercises'); const names = []; for (let k = 0; k < 8; k++) { await gotoEx(k); names.push(await text('.ex-name')); } assert(names[0].includes('事前疲労') && names[2].includes('マシン インクラインプレス') && names[4].includes('スーパーセット') && names[7].includes('アンダーハンド'), 'names: ' + names.join(' / '));
    await gotoEx(4); assert((await text('.tag.ss')).includes('スーパーセット') && (await text('.tag.ss')).includes('休憩なし'), 'superset tag'); assert((await page.$$eval('.tag', els => els.map(e => e.textContent).join('|'))).includes('プログレッシブ ・ セットごとに回数を増やす'), 'progressive tag'); assert((await text('.tag.ss')).includes('休憩なし') && (await text('.tag.ss')).includes('ペックデッキ → プレート'), 'pair names in tag'); const rows = await page.$$eval('.setrows .sr .nm', els => els.map(e => e.textContent)); assert(rows.length === 6 && rows[0].includes('セット1-1 ペックデッキ') && rows[0].includes('8回') && rows[1].includes('セット1-2 プレート') && rows[2].includes('セット2-1') && rows[5].includes('セット3-2') && rows[5].includes('12回'), 'pairs 8-10-12: ' + rows.join(','));
    // 1-1 完了 → 休憩なしで 1-2 へ。1-2 完了 → 休憩
    await page.click('[data-set="0"]'); await page.waitForTimeout(60); if ((await text('#wv')) === '—') await page.click('[data-qk]'); await page.click('#setDone'); await page.waitForTimeout(100); assert(!(await has('#rest:not([hidden])')), 'no rest between pair'); assert((await text('.cur-set .n')).includes('セット1-2'), 'moved to 1-2: ' + (await text('.cur-set .n'))); assert((await text('#toast')).includes('スーパーセット'), 'superset toast'); assert((await text('.cur-set .p')).includes('直後、休まずに'), 'pair purpose'); if ((await text('#wv')) === '—') await page.click('[data-qk]'); await page.click('#setDone'); await page.waitForSelector('#rest:not([hidden])'); assert((await text('#rnext')).includes('セット2-1 ペックデッキ'), 'rest then next pair: ' + (await text('#rnext'))); await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])');
    await gotoEx(5); assert(!(await has('.tag.ss')), 'no superset tag'); assert((await page.$$eval('.tag', els => els.map(e => e.textContent).join('|'))).includes('プログレッシブ'), 'progressive on side raise'); assert((await page.$$eval('.setrows .sr .nm', els => els.map(e => e.textContent))).length === 4, '3 main + drop');
    // 3セット目の完了 → 休憩なしでドロップセットへ
    for (let k = 0; k < 3; k++) { await page.click('[data-set="' + k + '"]'); await page.waitForTimeout(60); if ((await text('#wv')) === '—') await page.click('[data-qk="8"]'); await page.click('#setDone'); await page.waitForTimeout(80); if (await has('#rest:not([hidden])')) { assert(k < 2, 'no rest before drop'); await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])'); } }
    assert((await text('.cur-set .n')).includes('ドロップセット'), 'now on drop set'); assert((await text('#toast')).includes('休まずすぐ開始'), 'drop toast'); assert(!(await has('#rest:not([hidden])')), 'no rest timer'); await gotoEx(0); });  await T(G.workout, '完了→休憩タイマー（トップ・メイン 150秒/ウォームアップ 90秒）→自動で次セット。「飛ばす」で即次へ', async () => { await gotoEx(1); await page.click('[data-set="1"]'); await page.waitForTimeout(80); assert((await text('.cur-set .n')).includes('トップセット'), 'on TOP set'); if ((await text('#wv')) === '—') await page.click('[data-qk="20"]'); await setTime('2026-09-16T07:41:10+08:00'); await page.click('#setDone'); await page.waitForSelector('#rest:not([hidden])'); const rn = await text('#rn'); assert(rn === '2:30' || rn === '2:29', 'TOP rest ' + rn); assert((await text('#rnext')).includes('セット3 バックオフ'), 'next: ' + (await text('#rnext')));
    if (mode === 'db') { await page.waitForTimeout(250); await setTime('2026-09-16T07:42:00+08:00'); await page.reload(); await page.waitForFunction(() => !document.querySelector('#view .loading')); await goTab('workout'); await page.waitForSelector('#rest:not([hidden])'); const rl = await text('#rn'); assert(/^1:(3|4)\d$/.test(rl), 'rest continues after reload ~1:40: ' + rl); }
    await setTime('2026-09-16T08:40:00+08:00'); await page.waitForSelector('#setDone:not([hidden])', { timeout: 5000 }); assert((await text('.setrows .sr.cur .nm')).includes('セット3'), 'auto advance to set3'); await page.click('#setDone'); await page.waitForSelector('#rest:not([hidden])'); const r2 = await text('#rn'); assert(r2 === '2:30' || r2 === '2:29', 'BO rest ' + r2); assert(/マシン インクラインプレス.*セット1 メイン/.test(await text('#rnext')), 'next exercise: ' + (await text('#rnext'))); await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])'); });
  await T(G.workout, '代替種目名の上書きが保存され、マスタ名は不変', async () => { await gotoEx(2); assert((await text('.ex-name')).includes('マシン インクラインプレス'), 'ex3'); await page.click('#subBtn'); await dlgOk('フロアプレス'); assert((await text('.ex-name')) === 'フロアプレス', 'sub name shown'); assert((await text('.tag.sub')).includes('代替'), 'tag'); if (mode === 'db') { await page.waitForTimeout(200); const ex = await page.$eval('.ex-en', e => e.textContent); assert(rt.DB.plan_exercises['31'].nameJa.startsWith('マシン インクラインプレス'), 'master unchanged'); assert(rt.DB.log_workout['2026-09-16'].meta['31'].subName === 'フロアプレス', 'meta saved'); } });
  await T(G.workout, '違和感メモ・RPE が保存', async () => { await page.click('#noteBtn'); await page.waitForSelector('#exNote'); await page.fill('#exNote', 'right shoulder slight discomfort'); await page.click('[data-r="8"]'); await page.click('#exSave'); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(100); assert((await text('#noteBtn')).includes('●'), 'note marker'); if (mode === 'db') { await page.waitForTimeout(200); const m = rt.DB.log_workout['2026-09-16'].meta['31']; assert(m.note === 'right shoulder slight discomfort' && m.rpe === 8, 'meta ' + JSON.stringify(m)); } });
  await T(G.workout, 'フォーム動画アップロード（assets）と一覧。assets が null ならボタン非表示', async () => { if (mode === 'mock') { assert(!(await page.$eval('#formBtn', e => !e.hidden)), 'form button hidden'); return 'assets null → 非表示'; } assert(await page.$eval('#formBtn', e => !e.hidden), 'form button visible'); await page.click('#formBtn'); await page.waitForSelector('#mFile'); await page.setInputFiles('#mFile', { name: 'form.mp4', mimeType: 'video/mp4', buffer: Buffer.from('0123456789') }); await page.click('#mUp'); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(200); assert(rt.assets.length === 1 && rt.assets[0].type === 'video/mp4', 'uploaded'); const media = Object.values(rt.DB.log_media); assert(media.length === 1 && media[0].category === 'form' && media[0].assetId === rt.assets[0].id, 'log_media'); await goTab('summary'); assert(await has('.gallery .thumb video'), 'gallery shows video'); await goTab('workout'); return 'assets.upload → log_media.assetId → 一覧'; });
  await T(G.workout, '途中で閉じて再開すると同じ種目・セットから続けられる', async () => { await gotoEx(2); const before = await text('.ex-head .p'); if (mode === 'db') { await page.waitForTimeout(300); await page.reload(); await page.waitForFunction(() => !document.querySelector('#view .loading')); await goTab('workout'); } else { await goTab('today'); await goTab('workout'); } if (await has('#rest:not([hidden])')) { await page.click('#skipRest'); } await page.waitForSelector('#setDone:not([hidden])'); const after = await text('.ex-head .p'); assert(!(await has('#wuStart')), 'warmup not repeated'); assert(after.includes('種目 3/8'), 'resume at ex3: ' + after + ' (before ' + before + ')'); });
  await T(G.workout, '最終セット→次種目。最終種目→有酸素入力→今日へ戻る', async () => { for (let guard = 0; guard < 40; guard++) { if ((await text('#setDone')).includes('筋トレ完了')) break; if ((await text('#wv')) === '—') { const q = await page.$('[data-qk]'); if (q) await q.click(); else { await page.click('[data-pm="w:1"]'); } } await page.click('#setDone'); if (await has('#rest:not([hidden])')) { await page.click('#skipRest'); await page.waitForSelector('#setDone:not([hidden])'); } await page.waitForTimeout(40); } assert((await text('#setDone')).includes('筋トレ完了'), 'all done'); assert(await page.$$eval('.setrows .sr', els => els.every(e => e.classList.contains('done') || e.classList.contains('cur'))), 'all sets done'); await page.click('#setDone'); await page.waitForSelector('#cMin'); await page.fill('#cMin', '40'); await page.click('#cSave'); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(150); assert((await page.$eval('.tabs .on', e => e.dataset.tab)) === 'today', 'back to today'); assert((await page.$eval('[data-step="workout"]', e => e.className)).includes('done'), 'workout done'); assert((await text('[data-step="cardio"]')).includes('ウォーキング 40分'), 'cardio row'); });
  await shot('04-workout-done');
  await T(G.workout, 'Day3・Day7 はウォームアップ→有酸素のみ（筋トレ・腹筋/カーフなし）', async () => { await goTab('today'); await page.click('[data-shift="1"]'); await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 3'), 'day3'); const rows = await page.$$eval('.step', els => els.map(e => e.dataset.step)); assert(!rows.includes('workout') && !rows.includes('abscalves') && rows.indexOf('warmup') === rows.indexOf('cardio') - 1, 'warmup → cardio, no abs/calves: ' + rows.join(',')); await goTab('workout'); await page.waitForSelector('#wuStart'); assert((await text('#wuStart')) === '有酸素を始める', 'button text'); for (let id = 1; id <= 6; id++) { await page.click('[data-wuset="' + id + '"]'); await page.click('[data-wuset="' + id + '"]'); } await page.waitForFunction(() => document.querySelector('#wuProg').textContent.includes('6種 完了')); await page.click('#wuStart'); await page.waitForSelector('#rcardio'); assert((await text('.now .t')).includes('休み ・ 有酸素のみ'), 'rest card'); await goTab('today'); await page.click('[data-shift="-1"]'); await page.click('[data-shift="-1"]'); });
  await T(G.workout, '全7日確定版: Day2 Pull 8種目 / Day4 Legs 8種目 / Day5 Shoulder & Arms 8種目 / Day6 Pull 8種目。ドロップ「限界まで」とスーパーセットの組展開', async () => { await goTab('today'); const wk = async () => text('[data-step="workout"]'); try {
    await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 2') && (await wk()).includes('Pull ・ 8種目') && (await wk()).includes('Vバー ロウ（事前疲労）') && (await wk()).includes('ラックプル') && (await wk()).includes('EZバー カール'), 'Day2: ' + (await wk()));
    await page.click('[data-shift="1"]'); await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 4') && (await wk()).includes('Legs ・ 8種目') && (await wk()).includes('ダンベル RDL（事前疲労）') && (await wk()).includes('スモウスクワット（スーパーセット）'), 'Day4: ' + (await wk()));
    await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 5') && (await wk()).includes('Shoulder & Arms ・ 8種目') && (await wk()).includes('ウォームアップ: フロントレイズ') && (await wk()).includes('ロープ フェイスプル（スーパーセット）'), 'Day5: ' + (await wk()));
    await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 6') && (await wk()).includes('Pull ・ 8種目') && (await wk()).includes('ストレートアーム ラットエクステンション（事前疲労）') && (await wk()).includes('フェイスプル（スーパーセット）'), 'Day6: ' + (await wk()));
    } finally { for (let k = 0; k < 8 && !(await text('.date')).includes('9/16'); k++) await page.click('[data-shift="-1"]'); } assert((await text('h1')).startsWith('Day 1'), 'back to Day1');
    const r = await page.evaluate(() => { const t = window.__tl; const d = t.parseSetScheme('MAIN10-15x3,DROP*'); const p = t.expandPairSets(t.parseSetScheme('MAIN8,MAIN10,MAIN12'), ['A動作', 'B動作']); return { n: d.length, last: d[3], lastTxt: t.repsText(d[3]), pn: p.length, labels: p.map(x => t.setLabel(x)), moves: p.map(x => x.move).join('') }; });
    assert(r.n === 4 && r.last.setType === 'DROP' && r.last.min === 0 && r.lastTxt === '限界まで', 'DROP*: ' + JSON.stringify(r)); assert(r.pn === 6 && r.moves === 'ababab' && r.labels[0] === 'セット1-1 A動作' && r.labels[5] === 'セット3-2 B動作', 'pairs: ' + JSON.stringify(r.labels)); return 'Day2/4/5/6 の種目数と代表種目、DROP*=限界まで、スーパーセット 3組→6セット'; });

  // ============ 週 ============
  await goTab('summary'); await page.waitForSelector('#repText');
  await T(G.week, '体重グラフ（実測＋7日平均）。データ1日でも壊れない', async () => { assert(await has('.spark svg'), 'svg'); const pt = await page.$$eval('.spark svg .pt', els => els.length), ma = await page.$$eval('.spark svg .mapt', els => els.length); assert(pt === 1 && ma === 1, '1 measured point + 1 ma point: ' + pt + '/' + ma); assert((await page.$$eval('.spark svg polyline', els => els.length)) === 0, 'single day → no line'); assert(!errors.length, 'no errors'); });
  await T(G.week, '遵守率にウォームアップ・筋トレ・有酸素・食事・サプリ・水が含まれる', async () => { const st = await page.$eval('.stat', e => e.textContent); assert(st.includes('筋トレ') && st.includes('ウォームアップ 1/1') && st.includes('食事') && st.includes('有酸素') && st.includes('サプリ 71%') && st.includes('水 1/1'), st); const hist = await text('.hist'); assert(hist.includes('Day1') && hist.includes('ウォームアップ') && hist.includes('遅れ'), 'history table with 遅れ'); assert(await has('details .hist'), 'per-day planned/logged table'); });
  await T(G.week, 'コーチ向けレポート生成→コピーが実データと一致', async () => { const rep = await text('#repText'); assert(rep.startsWith('Week 1 (Sep 16–22) Report'), 'header'); assert(rep.includes('Weight: 72.6 → 72.6 kg (avg 72.6, 1/1 days measured)'), 'weight line: ' + rep.split('\n')[1]); assert(rep.includes('Workouts: 1/1 done, Warm-up: 1/1, Cardio: 1/1 (40 min)'), 'workouts line: ' + rep.split('\n')[2]); assert(rep.includes('Machine or Smith incline press: right shoulder slight discomfort') && rep.includes('meal 3 missed (eating out)'), 'notes: ' + rep); assert(rep.includes('Supplements: 71%') && rep.includes('Water: 1/1 days'), 'supp/water: ' + rep); assert(/Timing: \d+\/\d+ logged within 60 min of plan/.test(rep), 'timing line: ' + rep); await page.click('#copyRep'); await page.waitForTimeout(100); assert((await text('#toast')).includes('コピー'), 'copy toast'); });
  await T(G.week, 'CSV エクスポート。downloads が null ならボタン非表示', async () => { if (mode === 'mock') { assert(!(await page.$eval('#csvBtn', e => !e.hidden)), 'hidden'); return 'downloads null → 非表示'; } await page.click('#csvBtn'); await page.waitForTimeout(200); assert(rt.downloads.length === 1 && rt.downloads[0].filename === 'training-log-2026-09-16.csv' && rt.downloads[0].size > 200, 'saved ' + JSON.stringify(rt.downloads[0])); assert(rt.downloads[0].head.includes('"plannedAt","loggedAt"') && rt.downloads[0].head.includes('"times"'), 'csv has planned/logged columns: ' + rt.downloads[0].head.slice(0, 120)); return rt.downloads[0].filename + ' (' + rt.downloads[0].size + ' bytes)'; });
  await shot('05-summary');

  // ============ 欠測・できなかった ============
  await T(G.missed, '体重「測れなかった」→ 灰色「−」・理由表示・「いま」は次へ進む', async () => { await setTime('2026-09-17T06:45:00+08:00'); await goTab('today'); await page.click('[data-shift="1"]'); assert((await text('.date')).includes('9/17'), 'on 9/17'); await page.click('[data-open="weight"]'); await page.waitForSelector('#shNA'); await page.click('#shNA'); await pickReason('外泊・旅行'); await page.waitForTimeout(150);
    const m = await mark('weight'); assert(m.startsWith('na|chk na|−'), 'weight mark: ' + m); assert((await text('[data-step="weight"]')).includes('測れなかった（外泊・旅行）'), 'row text'); assert(!(await page.$('[data-step="weight"] .chk.on')), 'no green'); assert((await text('#now .t')).includes('リンゴ酢'), 'now moved on: ' + (await text('#now .t'))); if (mode === 'db') { await page.waitForTimeout(200); const w = rt.DB.log_weight['2026-09-17']; assert(w.skipped === true && w.reason === '外泊・旅行' && w.loggedAt, 'db ' + JSON.stringify(w)); } });
  await T(G.missed, '測れなかった → 翌日通常記録 → グラフは欠測日をつながず・平均は実測のみ・週まとめ/レポート/CSV が正しい', async () => { await setTime('2026-09-18T06:45:00+08:00'); await goTab('today'); await page.click('[data-shift="1"]'); assert((await text('.date')).includes('9/18'), 'on 9/18'); await page.fill('#nowW', '72.0'); await page.click('#nowBtn'); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').dataset.mark === 'ok');
    await goTab('summary'); await page.waitForSelector('#repText'); const pts = await page.$$eval('.spark svg .pt', els => els.map(e => e.dataset.date + '=' + e.dataset.v)); assert(pts.join(',') === '2026-09-16=72.6,2026-09-18=72', 'points ' + pts.join(',')); assert((await page.$$eval('.spark svg polyline', els => els.length)) === 0, '2 non-adjacent days → no connecting line'); const ma = await page.$$eval('.spark svg .mapt', els => els.map(e => e.dataset.date + '=' + e.dataset.v)); assert(ma.includes('2026-09-18=72.3'), '7日平均は実測 (72.6+72.0)/2=72.3: ' + ma.join(','));
    assert((await page.$eval('.stat', e => e.textContent)).includes('体重 2/3 日 測定'), 'measured days'); const rep = await text('#repText'); assert(rep.includes('Weight: 72.6 → 72 kg (avg 72.3, 2/3 days measured, skipped: travel×1)'), 'report weight line: ' + rep.split('\n')[1]); assert(rep.includes('09/17 weight missed (travel)'), 'notes auto: ' + rep); assert((await text('#missedBlock')).includes('9/17') && (await text('#missedBlock')).includes('外泊・旅行'), 'missed block');
    if (mode === 'db') { await page.click('#csvBtn'); await page.waitForTimeout(200); const dl = rt.downloads[rt.downloads.length - 1]; assert(dl.head.includes('"skipped","reason"'), 'csv columns: ' + dl.head.slice(0, 100)); assert(dl.size > 0); } return 'points=' + pts.join(',') + ' / ma(9/18)=72.3'; });
  await T(G.missed, 'あとで測れたら数値保存で skipped 解除。「記録を取り消す」で未記録に戻る', async () => { await goTab('today'); await page.click('[data-shift="-1"]'); assert((await text('.date')).includes('9/17'), 'on 9/17'); await page.click('[data-open="weight"]'); await page.waitForSelector('#shSave'); await page.fill('#shW', '72.3'); await page.click('#shSave'); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').dataset.mark === 'ok'); assert((await text('[data-step="weight"]')).includes('72.3kg'), 'measured later'); if (mode === 'db') { await page.waitForTimeout(150); assert(!rt.DB.log_weight['2026-09-17'].skipped, 'skipped cleared'); }
    await page.click('[data-chk="weight"]'); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').dataset.mark === ''); assert((await text('#toast')).includes('取り消しました'), 'cancel toast'); await page.click('#toast button'); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').dataset.mark === 'ok'); await page.click('[data-open="weight"]'); await page.waitForSelector('#shCancel'); await page.click('#shCancel'); await dlgOk(); await page.waitForFunction(() => document.querySelector('[data-step="weight"]').dataset.mark === ''); if (mode === 'db') { await page.waitForTimeout(150); assert(!rt.DB.log_weight['2026-09-17'], 'db doc removed'); } });
  await T(G.missed, 'サプリ「今日はなし（理由）」→ 灰色−・理由表示。再タップで取り消し', async () => { await page.click('[data-open="supp:after_meal"]'); await page.waitForSelector('#suppNA'); await page.click('#suppNA'); await pickReason('切れていた'); await page.waitForTimeout(150); const m = await mark('supp:after_meal'); assert(m.startsWith('na|chk na|−'), 'supp mark ' + m); assert((await text('[data-step="supp:after_meal"]')).includes('今日はなし（切れていた）'), 'reason line'); await page.click('[data-chk="supp:after_meal"]'); await page.waitForFunction(() => document.querySelector('[data-step="supp:after_meal"]').dataset.mark === ''); assert((await text('#toast')).includes('取り消しました'), 'undo toast');
    // ルーティンは長押し
    await page.dispatchEvent('[data-chk="routine:1"]', 'pointerdown'); await page.waitForTimeout(700); await page.dispatchEvent('[data-chk="routine:1"]', 'pointerup'); await pickReason('忘れた'); await page.waitForTimeout(150); assert((await mark('routine:1')).startsWith('na|'), 'routine long-press NA'); assert((await text('[data-step="routine:1"]')).includes('今日はなし（忘れた）'), 'routine reason'); });
  await T(G.missed, '筋トレ「できなかった（理由）」→ Day をずらすと翌日以降の Day が 1 つ戻る。取り消しで元に戻る', async () => { await setTime('2026-09-19T08:00:00+08:00'); await page.click('[data-shift="1"]'); await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 4'), '9/19 = Day4'); await page.click('[data-chk="workout"]'); await page.waitForSelector('[data-choice="1"]'); await page.click('[data-choice="1"]'); await pickReason('仕事'); await page.waitForSelector('[data-choice="0"]'); await page.click('[data-choice="0"]'); await page.waitForTimeout(150);
    assert((await mark('workout')).startsWith('na|chk na|−'), 'workout na'); assert((await text('[data-step="workout"]')).includes('できなかった（仕事）') && (await text('[data-step="workout"]')).includes('Day をずらす'), 'row'); if (mode === 'db') { await page.waitForTimeout(150); const dd = rt.DB.log_daily['2026-09-19']; assert(dd.workoutMissed && dd.workoutMissed.shift === true && dd.workoutMissed.reason === '仕事', 'log_daily ' + JSON.stringify(dd.workoutMissed)); }
    await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 4'), '9/20 → Day4 (shifted)'); await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 5'), '9/21 → Day5'); await page.click('[data-shift="-1"]'); await page.click('[data-shift="-1"]');
    await page.click('[data-chk="workout"]'); await page.waitForFunction(() => document.querySelector('[data-step="workout"]').dataset.mark === ''); await page.click('[data-shift="1"]'); assert((await text('h1')).startsWith('Day 5'), '取り消し後 9/20 → Day5'); await page.click('[data-shift="-1"]');
    await page.click('[data-chk="cardio"]'); await page.waitForSelector('[data-choice="1"]'); await page.click('[data-choice="1"]'); await pickReason('体調不良'); await page.waitForTimeout(150); assert((await text('[data-step="cardio"]')).includes('できなかった（体調不良）'), 'cardio missed');
    await goTab('summary'); await page.waitForSelector('#missedBlock'); const mb = await text('#missedBlock'); assert(mb.includes('有酸素') && mb.includes('体調不良') && mb.includes('忘れた') && !mb.includes('切れていた'), 'missed block lists cardio + routine (cancelled supp NA excluded): ' + mb); assert((await text('#repText')).includes('cardio missed (sick)'), 'report notes cardio'); for (let i = 0; i < 3; i++) { await goTab('today'); await page.click('[data-shift="-1"]'); } await setTime('2026-09-16T08:40:00+08:00'); });

  await T(G.common, 'db スキーマ: log_weight{value,unit,skipped,skipReason,loggedAt} / warmup{completed,minutes,loggedAt} / meals{status: plan|substitute|skip|photo, photoId, reason} / log_daily{dayNo,dayName,notes,skippedItems[]}', async () => { if (mode === 'mock') return 'db のみ';
    const w = rt.DB.log_weight['2026-09-16']; assert(w.value === 72.6 && w.unit === 'kg' && w.skipped === false && w.loggedAt, 'weight ' + JSON.stringify(w));
    const wu = rt.DB.log_workout['2026-09-16'].warmup; assert(wu.completed === true && wu.minutes >= 1 && wu.loggedAt, 'warmup ' + JSON.stringify(wu));
    const meals = rt.DB.log_meals['2026-09-16'].meals; const sts = Object.values(meals).map(m => m.status); assert(sts.every(x => ['plan', 'substitute', 'skip', 'photo'].includes(x)), 'statuses ' + sts.join(',')); assert(Object.values(meals).every(m => 'photoId' in m && 'reason' in m && m.loggedAt), 'photoId/reason/loggedAt'); const sk = Object.values(meals).find(m => m.status === 'skip'); if (sk) assert(sk.reason, 'skip reason persisted');
    const dd = rt.DB.log_daily['2026-09-17']; assert(dd && dd.dayName === 'Pull' && Array.isArray(dd.skippedItems) && 'notes' in dd, 'daily ' + JSON.stringify(dd)); const dd16 = rt.DB.log_daily['2026-09-16']; assert(dd16 && dd16.skippedItems.some(x => x.item === 'meal 3'), 'skippedItems lists meal 3: ' + JSON.stringify(dd16 && dd16.skippedItems)); return 'statuses=' + sts.join(',') + ' / 9/16 skippedItems=' + dd16.skippedItems.map(x => x.item).join('|'); });

  // ============ 写真で記録 ============
  const G2 = '写真で記録';
  const makeImageFile = (w, h, noise) => page.evaluate(([w, h, noise]) => new Promise(res => { const cv = document.createElement('canvas'); cv.width = w; cv.height = h; const ctx = cv.getContext('2d'); if (noise) { const id = ctx.createImageData(w, h); const a = id.data; for (let i = 0; i < a.length; i += 4) { a[i] = Math.random() * 255; a[i + 1] = Math.random() * 255; a[i + 2] = Math.random() * 255; a[i + 3] = 255; } ctx.putImageData(id, 0, 0); } else { const g = ctx.createLinearGradient(0, 0, w, h); g.addColorStop(0, '#c33'); g.addColorStop(1, '#3c3'); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); } cv.toBlob(b => { window.__img = new File([b], 'meal.' + (noise ? 'png' : 'jpg'), { type: b.type }); res({ size: b.size, type: b.type }); }, noise ? 'image/png' : 'image/jpeg', 0.95); }), [w, h, noise]);
  const setPhoto = () => page.evaluate(() => { const inp = document.querySelector('#phFile'); const dt = new DataTransfer(); dt.items.add(window.__img); inp.files = dt.files; inp.dispatchEvent(new Event('change')); });
  await T(G2, '写真→推定→修正→記録→合計に反映→取り消し→合計から消える', async () => { await goTab('today'); assert((await text('.date')).includes('9/16'), 'on 9/16');
    if (mode === 'mock') { await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mChange'); assert(!(await has('#mPhoto')), 'sample null → 写真ボタン非表示'); await closeSheet(); return 'sample null → 写真ボタン非表示（テキスト入力のみ）'; }
    const total = async () => Number((await page.$eval('.card', e => e.textContent)).match(/カロリー ([\d,]+)/)[1].replace(/,/g, ''));
    const base = await total(); const nAssets = rt.assets.length;
    await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mPhoto'); await page.click('#mPhoto'); await page.waitForSelector('#phFile');
    await makeImageFile(3000, 2000, false); await setPhoto(); await page.waitForSelector('#phEst'); const dim = await text('#photoPanel .num'); assert(dim.startsWith('1280×853'), 'resized to 1280×853: ' + dim);
    await page.fill('#phNote', 'ご飯は少なめ'); await page.click('#phEst'); await page.waitForSelector('#phSave', { timeout: 15000 });
    const sc = rt.sampleCalls[rt.sampleCalls.length - 1]; assert(sc.hasImage && sc.imageType === 'image/jpeg' && sc.imageSize < 1000000 && sc.tier === 'default', 'sample got resized jpeg on default tier: ' + JSON.stringify(sc)); assert(sc.prompt.length > 0);
    assert((await page.$$eval('.photo .est .it', els => els.length)) === 2, 'two item rows'); assert((await text('.photo .conf')).includes('推定の確度: 中'), 'confidence'); assert((await text('.photo .row2')).includes('合計 652kcal※'), 'total 652※');
    await page.click('[data-phg="0:10"]'); await page.waitForSelector('#phSave'); assert((await text('.photo .est .it')).includes('210g'), 'grams +10'); await page.click('[data-phoff="1"]'); await page.waitForSelector('#phSave'); assert((await text('.photo .row2')).includes('合計 328kcal※'), 'exclude item → 328: ' + (await text('.photo .row2')));
    await page.click('#phSave'); await page.waitForSelector('#sheet', { state: 'hidden' }); await page.waitForTimeout(250);
    const row = await text('[data-step="meal:5"]'); assert(row.includes('📷') && row.includes('白ご飯210g') && /約328kcal※/.test(row), 'row: ' + row); assert((await total()) === base + 328, 'total +328: ' + (await total()) + ' vs ' + base);
    assert(rt.assets.length === nAssets + 1 && rt.assets[nAssets].type === 'image/jpeg', 'photo uploaded to assets'); const med = Object.values(rt.DB.log_media).find(m => m.category === 'meal'); assert(med && med.mealNo === 5 && med.assetId === rt.assets[nAssets].id, 'log_media meal link'); const fd = Object.values(rt.DB.foods).find(f => f.source === 'ai_photo'); assert(fd && fd.nameJa === '白ご飯' && Math.round(fd.kcal) === 156, 'foods ai_photo per100g: ' + JSON.stringify(fd)); assert(rt.DB.log_meals['2026-09-16'].meals[5].photo.assetId === med.assetId, 'meal photo ref');
    await page.click('[data-photo="5"]'); await page.waitForSelector('#dlg img.thumb'); assert((await page.$eval('#dlg img.thumb', e => e.getAttribute('src'))).startsWith('/_blob/'), 'thumbnail from assets'); await page.click('#dlgNo'); await page.waitForSelector('#dlg', { state: 'hidden' });
    await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === ''); assert((await total()) === base, 'cancel → total back');
    await goTab('summary'); await page.waitForSelector('#repText'); await goTab('today'); return '1280×853 JPEG ' + Math.round(sc.imageSize / 1024) + 'KB を送信 / 白ご飯 210g=328kcal※ を記録'; });
  await T(G2, '推定 JSON の parse 失敗時にアプリが落ちず、手入力に切替できる', async () => { if (mode === 'mock') return '写真ボタン非表示のため対象外'; await page.click('[data-open="meal:5"]'); await page.waitForSelector('#mPhoto'); await page.click('#mPhoto'); await page.waitForSelector('#phFile'); await makeImageFile(800, 600, false); await setPhoto(); await page.waitForSelector('#phEst'); await page.fill('#phNote', 'BAD'); await page.click('#phEst'); await page.waitForSelector('#phManual', { timeout: 15000 }); assert((await text('.photo .pending')).includes('推定結果を読み取れませんでした'), 'error line: ' + (await text('.photo .pending'))); await page.click('#phManual'); await page.waitForSelector('#freeTxt'); assert(!(await has('#photoPanel')) && !(await page.$eval('#sub', e => e.hidden)), 'switched to manual'); assert(!errors.length, 'no page errors'); await closeSheet(); });
  await T(G2, '画像非対応（limits.images=false）環境でボタンが隠れる', async () => { if (mode === 'mock') return 'sample null で非表示（上で確認）'; const p2 = await newPage({ noImages: true }); await p2.waitForTimeout(600); await p2.click('.tabs [data-tab="today"]'); await p2.click('[data-open="meal:5"]'); await p2.waitForSelector('#mChange'); assert(!(await p2.$('#mPhoto')), 'no photo button'); assert(await p2.$('#freeTxt') || true, 'text input still there'); await p2.close(); });
  await T(G2, 'assets null で推定だけ動く（写真はメモリ保持、記録は保存）', async () => { if (mode === 'mock') return 'db のみ'; const p2 = await newPage({ noAssets: true }); await p2.waitForTimeout(600); await p2.click('.tabs [data-tab="today"]'); const nAssets = rt.assets.length; await p2.click('[data-open="meal:5"]'); await p2.waitForSelector('#mPhoto'); await p2.click('#mPhoto'); await p2.waitForSelector('#phFile');
    await p2.evaluate(() => new Promise(res => { const cv = document.createElement('canvas'); cv.width = 600; cv.height = 400; cv.getContext('2d').fillStyle = '#c93'; cv.getContext('2d').fillRect(0, 0, 600, 400); cv.toBlob(b => { const inp = document.querySelector('#phFile'); const dt = new DataTransfer(); dt.items.add(new File([b], 'm.jpg', { type: 'image/jpeg' })); inp.files = dt.files; inp.dispatchEvent(new Event('change')); res(); }, 'image/jpeg', 0.9); }));
    await p2.waitForSelector('#phEst'); await p2.click('#phEst'); await p2.waitForSelector('#phSave', { timeout: 15000 }); await p2.click('#phSave'); await p2.waitForSelector('#sheet', { state: 'hidden' }); await p2.waitForTimeout(250);
    assert(rt.assets.length === nAssets, 'no upload'); const meal = rt.DB.log_meals['2026-09-16'].meals[5]; assert(meal && meal.photo && !meal.photo.assetId && meal.items.length === 2, 'recorded without assetId'); assert((await p2.locator('[data-step="meal:5"]').textContent()).includes('📷'), 'camera icon'); await p2.click('[data-photo="5"]'); await p2.waitForSelector('#dlg:not([hidden])'); assert((await p2.$eval('#dlg', e => e.textContent)).includes('保存されていません') || await p2.$('#dlg img.thumb'), 'photo dialog'); await p2.close();
    // 後始末: メインページで取り消し
    await page.reload(); await page.waitForFunction(() => !document.querySelector('#view .loading')); await goTab('today'); await page.click('[data-chk="meal:5"]'); await page.waitForFunction(() => document.querySelector('[data-step="meal:5"]').dataset.mark === ''); });
  await T(G2, '縦長・横長・大きい写真（10MB超）で送信前にリサイズ（長辺1280px、JPEG 0.8）して成功する', async () => { const r = await page.evaluate(async () => { const mk = (w, h, noise) => new Promise(res => { const cv = document.createElement('canvas'); cv.width = w; cv.height = h; const ctx = cv.getContext('2d'); if (noise) { const id = ctx.createImageData(w, h); const a = id.data; for (let i = 0; i < a.length; i += 4) { a[i] = Math.random() * 255; a[i + 1] = Math.random() * 255; a[i + 2] = Math.random() * 255; a[i + 3] = 255; } ctx.putImageData(id, 0, 0); } else { ctx.fillStyle = '#48c'; ctx.fillRect(0, 0, w, h); } cv.toBlob(b => res(new File([b], 'x', { type: b.type })), noise ? 'image/png' : 'image/jpeg', 0.95); });
    const out = {}; const big = await mk(3200, 2400, true); const rb = await window.__tl.resizeImage(big, 1280, 0.8); out.big = { inSize: big.size, w: rb.width, h: rb.height, type: rb.blob.type, outSize: rb.blob.size };
    const land = await mk(4000, 2000, false); const rl = await window.__tl.resizeImage(land); out.land = { w: rl.width, h: rl.height }; const port = await mk(1500, 3000, false); const rp = await window.__tl.resizeImage(port); out.port = { w: rp.width, h: rp.height }; const small = await mk(640, 480, false); const rs = await window.__tl.resizeImage(small); out.small = { w: rs.width, h: rs.height }; return out; });
    assert(r.big.inSize > 10 * 1024 * 1024, 'noise png > 10MB: ' + r.big.inSize); assert(r.big.w === 1280 && r.big.h === 960 && r.big.type === 'image/jpeg' && r.big.outSize < 1.5 * 1024 * 1024, 'big → ' + JSON.stringify(r.big)); assert(r.land.w === 1280 && r.land.h === 640, 'landscape ' + JSON.stringify(r.land)); assert(r.port.w === 640 && r.port.h === 1280, 'portrait ' + JSON.stringify(r.port)); assert(r.small.w === 640 && r.small.h === 480, 'small unchanged'); return (r.big.inSize / 1048576).toFixed(1) + 'MB PNG → ' + (r.big.outSize / 1024).toFixed(0) + 'KB JPEG 1280×960'; });

  // ============ 共通（後で） ============
  await T(G.common, '英略語（W/MAIN/TOP/BO/DROP/PRE/FINAL）がUIに出ない', async () => { const re = /(^|[^A-Za-z])(WU|W|MAIN|TOP|BO|DROP|PRE|FINAL)([^A-Za-z]|$)/; for (const tab of ['today', 'workout', 'summary']) { await goTab(tab); const txt = await page.$eval('#view', e => e.innerText); const m = re.exec(txt); assert(!m, tab + ': ' + (m && m[0])); } });
  await T(G.common, '数だけの表示（7種、1種）がない', async () => { for (const tab of ['today', 'workout', 'summary']) { await goTab(tab); const txt = await page.$eval('#view', e => e.innerText); const bad = txt.split('\n').filter(l => /サプリ\s*\d+種/.test(l) || /^\s*\d+種(目)?\s*$/.test(l)); assert(!bad.length, tab + ': ' + bad.join(' | ')); } });
  await T(G.common, '同日に2回開いても二重保存されない', async () => { if (mode === 'mock') return 'db のみ'; const before = JSON.stringify(rt.DB); const p2 = await newPage(); await p2.waitForTimeout(800); assert(!(await p2.$('#view .loading')), 'second page rendered'); const after = JSON.stringify(rt.DB); assert(before === after, 'second open changed db'); const counts = Object.fromEntries(Object.entries(rt.DB).map(([k, v]) => [k, Object.keys(v).length])); assert(counts.plan_days === 7 && counts.plan_exercises === 40 && counts.plan_supplements === 7 && counts.plan_warmup === 6, JSON.stringify(counts)); await p2.close(); return 'docs: ' + JSON.stringify(counts); });
  await browser.close();
  return errors;
}
(async () => {
  const errs = {};
  for (const mode of ['mock', 'db']) { errs[mode] = await run(mode); if (errs[mode].length) console.error('[' + mode + '] page errors:\n' + errs[mode].join('\n')); }
  // ---- TEST.md ----
  const groups = [...new Set(results.map(r => r.group))];
  let md = '# テスト結果（自動生成: `npm run e2e:artifact`）\n\n実行日: ' + new Date().toISOString().slice(0, 10) + ' ／ 固定時刻 2026-09-16 06:50 (Asia/Manila) ／ Chromium 390×844\n\n';
  md += '- **mock**: `window.claude` なし → メモリ上のモックモード\n- **db**: `claude.use("db"/"assets"/"sample"/"downloads")` を疑似ランタイムで注入（db は Node 側に永続し、再読み込み・二重オープンを再現。実際の claude.ai ランタイムではなく API 形状を模したもの）\n\n';
  const fails = results.filter(r => r.mock === '✗' || r.db === '✗').length;
  md += '合計 ' + results.length + ' 項目 ／ NG ' + fails + ' 件 ／ ページエラー mock ' + errs.mock.length + ' 件・db ' + errs.db.length + ' 件\n\n';
  groups.forEach(g => { md += '## ' + g + '\n\n| 項目 | mock | db | 備考 |\n|---|:-:|:-:|---|\n'; results.filter(r => r.group === g).forEach(r => { md += '| ' + r.name + ' | ' + r.mock + ' | ' + r.db + ' | ' + r.note.replace(/\|/g, '/') + ' |\n'; }); md += '\n'; });
  md += `## テスト中に見つけて修正した内容

| # | 症状 | 原因 | 修正 |
|---|---|---|---|
| 1 | db モードで読み込み直後に「foods に egg_whole がありません」 | 全コレクションが揃う前の中間スナップショットで描画していた | \`store.ready\` が立つまで描画しない。さらに \`planToItems\` は foods 欠損でも例外を出さず栄養 0 で仮置き、\`render()\` は例外を捕まえて「表示エラー／再読み込み」カードを出す |
| 2 | 食事を「半分」「変更」で記録すると白米の基準（炊飯後/生米）表示が消える | 記録品目の短縮名生成で括弧内を落としていた | \`itemShort\` が rice_cooked / rice_raw に「（炊飯後基準）」「（生米基準）」を付ける |
| 3 | 途中で閉じて再開すると最初の未完了セットに戻る（前の種目へ飛ぶ） | 再開位置を保持していなかった | 日付ごとの現在位置を localStorage（軽い用途）に保持し、同じ種目・セットから再開 |
| 4 | ウォームアップで 6 つ目を ✓ した瞬間に筋トレ画面へ遷移し「始める」を押せない（前版） | 完了判定で即遷移していた | 「始める」を押すまでウォームアップ画面に留まる。セットカウンター方式に変更 |
| 5 | 提案重量 TOP が「TOP の半分」等の英略語を含む | 文言の残り | 「トップの半分」に統一。UI 全体を英略語なしで検証 |
| 6 | 実機で「取り消し」「プランに戻す」「代替種目」「飛ばす」が反応しない | claude.ai のアーティファクトは sandbox iframe で \`confirm()\` / \`prompt()\` が無効（常に false / null）。テスト環境では自動承認されていて気づけなかった | ページ内ダイアログ（askConfirm / askText / askTime）に全面置換。テストもダイアログを実際に操作する方式に変更 |
| 7 | スキップにすると緑✓とスキップ表示が同時に出る | 「記録あり」を一律 done 扱いにしていた | 状態を 未記録○ / プラン通り緑✓ / 変更あり黄✓ / スキップ赤− の 4 種に統一。緑✓はプラン通りのみ |
| 8 | 行の時刻がプランの予定時刻のままで実績が残らない | time(HH:mm) だけ保存し予定と区別していなかった | すべての記録に loggedAt(ISO 8601) を保存。行は実績を太字＋予定を小さく、60 分以上ズレは黄色。タップで時刻修正。タイマー（15 分・休憩）は loggedAt からの時刻差で算出し、再読み込み後も残り時間が続く |
| 9 | 体重を測れない日の扱いが無く、欠測日も直線でつながっていた | 欠測の概念が無かった | log_weight に skipped/reason を保存。行は灰色「−」、「いま」は次へ進む。グラフは隣り合う日だけ線で結び、7 日平均は暦 7 日窓の実測のみ。週まとめ「体重 N/M 日 測定」、レポート「(N/M days measured, skipped: travel×2)」、CSV に skipped/reason 列。食事・サプリ・ルーティン・筋トレ・有酸素にも理由つきの「できなかった」を追加し、週まとめのブロックとレポート Notes に自動集計 |
| 10 | 写真からの推定（新機能） | — | 送信前に長辺 1280px / JPEG 0.8 に縮小、\`sample.limits().images\` が無い環境では写真ボタンを隠す、assets が無ければ写真はメモリ保持で推定・記録のみ、推定 JSON の検証に失敗しても落ちずに「手入力に切替」できることを確認 |
| 11 | コーチ回答の反映で食事シートの補足（「筋トレ後の食事 ・ 必ず摂る」）が状態バッジと同じ見た目になり、テストでも状態バッジと取り違えた | 補足を badge クラスで描画していた | 補足は薄字の注記に変更。種目・セット構成（全セット10〜12回・最終セット −30%）・食事・サプリ・腹筋ルーティン・db スキーマ（log_weight value/unit/skipped、warmup.completed、meals.status、log_daily.skippedItems）を SEED_VERSION 4 で差し替え、休みの日は ウォームアップ→腹筋→有酸素 の順に |
| 12 | Day 1 Push 確定版: ドロップセットの前に休憩タイマーが出て「直後にすぐ」ができない。スーパーセット・プログレッシブの意味が画面に無い | セット種類ごとの休憩・説明が無かった | 次がドロップセットなら休憩なしで即開始（トースト「休まずすぐ開始」）、目安は直前 ×0.7。種目に「スーパーセット ・ 同時に2種目」「プログレッシブ ・ セットごとに回数を増やす」タグ。SEED_VERSION 5 で Day 1 を 8 種目（事前疲労＋7）に差し替え |
| 13 | スーパーセットが 1 種目 1 重量の扱いで、2 動作目を休憩なしで続ける流れが無い。水の記録がルーティン行の中に埋もれる。腹筋・カーフの置き場所が無い | 種目=1 動作の前提だった | pair を持つ種目は各セットを「1-1（A）→ 1-2（B）」に展開し、1-1 の後は休憩なし（トースト）。水タブ（+500/+350/−500、達成で緑、log_daily.waterMl）。トレーニング日はウォームアップ直後に 腹筋・カーフ 画面（コーチ確認待ち、完了チェックのみ）。全 7 日を SEED_VERSION 6 に差し替え、DROP* = 限界まで |

## 実行方法

\`\`\`
npm run e2e:artifact   # Playwright + Chromium。mock → db の順に実行し、この TEST.md を上書き
\`\`\`

db モードの「疑似ランタイム」は \`claude.use()\` の API 形状（db.collection/doc/get/set/delete/onSnapshot、assets.upload、sample.json、downloads.save）を模したもので、実際の claude.ai ランタイムでの動作確認は公開版を開いて行う。
`;
  fs.writeFileSync(path.join(__dirname, '..', 'artifact', 'TEST.md'), md);
  console.log('\n' + results.length + ' items, ' + fails + ' NG. → artifact/TEST.md');
  if (fails || errs.mock.length || errs.db.length) process.exit(1);
})().catch(e => { console.error(e); process.exit(1); });
